export const questoesCSS = [
    {
        identificador: "q1",
        pergunta: "Qual propriedade CSS é usada para definir a cor do texto?",
        alternativaA: "a) text-color",
        alternativaB: "b) color",
        alternativaC: "c) font-color",
        alternativaD: "d) text-style",
    },
    {
        identificador: "q2",
        pergunta: "Em CSS, qual seletor é usado para selecionar um elemento pelo seu atributo 'id'?",
        alternativaA: "a) #elemento",
        alternativaB: "b) #elemento",
        alternativaC: "c) .elemento",
        alternativaD: "d) elemento",
    },
    {
        identificador: "q3",
        pergunta: "Qual propriedade CSS é usada para adicionar margem interna (espaço interno) a um elemento?",
        alternativaA: "a) padding",
        alternativaB: "b) space",
        alternativaC: "c) margin",
        alternativaD: "d) inner-space",
    },
    {
        identificador: "q4",
        pergunta: "Em CSS, qual propriedade é usada para alterar o estilo do cursor do mouse quando passa sobre um elemento?",
        alternativaA: "a) mouse-cursor",
        alternativaB: "b) cursor",
        alternativaC: "c) pointer",
        alternativaD: "d) hover",
    },
    {
        identificador: "q5",
        pergunta: "Qual propriedade CSS é usada para controlar o espaçamento entre as linhas do texto?",
        alternativaA: "a) line-height",
        alternativaB: "b) spacing",
        alternativaC: "c) line-spacing",
        alternativaD: "d) text-spacing",
    },
    {
        identificador: "q6",
        pergunta: "Em CSS, qual seletor é usado para selecionar todos os elementos de uma lista não ordenada?",
        alternativaA: "a) ul > li",
        alternativaB: "b) ul li",
        alternativaC: "c) unordered-list",
        alternativaD: "d) ul + li",
    },
    {
        identificador: "q7",
        pergunta: "Qual propriedade CSS é usada para adicionar sombra a um elemento, como uma caixa de texto?",
        alternativaA: "a) box-shadow",
        alternativaB: "b) text-shadow",
        alternativaC: "c) shadow",
        alternativaD: "d) element-shadow",
    },
    {
        identificador: "q8",
        pergunta: "Em CSS, qual propriedade é usada para definir o tamanho da fonte de um elemento?",
        alternativaA: "a) font-size",
        alternativaB: "b) text-size",
        alternativaC: "c) font",
        alternativaD: "d) size-font",
    },
    {
        identificador: "q9",
        pergunta: "Qual propriedade CSS é usada para tornar o texto em caixa alta (maiúsculas)?",
        alternativaA: "a) text-transform",
        alternativaB: "b) uppercase",
        alternativaC: "c) text-transform: uppercase",
        alternativaD: "d) transform: uppercase",
    },
    {
        identificador: "q10",
        pergunta: "Em CSS, qual propriedade é usada para criar um efeito de transição suave em uma mudança de estilo?",
        alternativaA: "a) transition-effect",
        alternativaB: "b) transition",
        alternativaC: "c) smooth-transition",
        alternativaD: "d) style-transition",
    },
];
