export const questoesHtml = [
    {
        identificador: "q1",
        pergunta: "Qual tag HTML é usada para criar uma lista não ordenada?",
        alternativaA: "a) &lt;ul&gt;",
        alternativaB: "b) &lt;ol&gt;",
        alternativaC: "c) &lt;li&gt;",
        alternativaD: "d) &lt;dl&gt;",
    },
    {
        identificador: "q2",
        pergunta: "Qual atributo HTML é usado para definir o texto alternativo de uma imagem?",
        alternativaA: "a) src",
        alternativaB: "b) alt",
        alternativaC: "c) href",
        alternativaD: "d) link",
    },
    {
        identificador: "q3",
        pergunta: "Qual elemento HTML é utilizado para criar um hiperlink?",
        alternativaA: "a) &lt;url&gt;",
        alternativaB: "b) &lt;link&gt;",
        alternativaC: "c) &lt;a&gt;",
        alternativaD: "d) &lt;hyper&gt;",
    },
    {
        identificador: "q4",
        pergunta: "Em HTML, qual tag é usada para criar uma tabela?",
        alternativaA: "a) &lt;table&gt;",
        alternativaB: "b) &lt;tab&gt;",
        alternativaC: "c) &lt;tr&gt;",
        alternativaD: "d) &lt;td&gt;",
    },
    {
        identificador: "q5",
        pergunta: "Qual atributo HTML é usado para definir o título de uma página?",
        alternativaA: "a) &lt;header&gt;",
        alternativaB: "b) &lt;title&gt;",
        alternativaC: "c) &lt;h1&gt;",
        alternativaD: "d) &lt;head&gt;",
    },
    {
        identificador: "q6",
        pergunta: "Qual tag HTML é usada para criar um parágrafo?",
        alternativaA: "a) &lt;p&gt;",
        alternativaB: "b) &lt;paragraph&gt;",
        alternativaC: "c) &lt;para&gt;",
        alternativaD: "d) &lt;text&gt;",
    },
    {
        identificador: "q7",
        pergunta: "Qual elemento HTML é usado para definir um estilo em linha (inline)?",
        alternativaA: "a) &lt;css&gt;",
        alternativaB: "b) &lt;style&gt;",
        alternativaC: "c) &lt;inline&gt;",
        alternativaD: "d) &lt;i&gt;",
    },
    {
        identificador: "q8",
        pergunta: "Em HTML, qual tag é usada para criar um campo de entrada de texto?",
        alternativaA: "a) &lt;input&gt;",
        alternativaB: "b) &lt;text&gt;",
        alternativaC: "c) &lt;textbox&gt;",
        alternativaD: "d) &lt;field&gt;",
    },
    {
        identificador: "q9",
        pergunta: "Qual atributo HTML é usado para aplicar estilo a um elemento?",
        alternativaA: "a) class",
        alternativaB: "b) style",
        alternativaC: "c) format",
        alternativaD: "d) type",
    },
    {
        identificador: "q10",
        pergunta: "Em HTML, qual tag é usada para criar uma linha horizontal?",
        alternativaA: "a) &lt;line&gt;",
        alternativaB: "b) &lt;hr&gt;",
        alternativaC: "c) &lt;break&gt;",
        alternativaD: "d) &lt;hline&gt;",
    },
];